config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index'

  get '/galleries', to:'galleries#index'
  get '/galleries/new', to:'galleries#new'
  post '/galleries', to:'galleries#create'
  get '/galleries/:id', to:'galleries#show'
  get '/galleries/:id/edit', to: 'galleries#edit'
  patch '/galleries/:id', to: 'galleries#update'
  delete '/galleries/:id', to: 'galleries#destroy'

  get '/programs', to: 'programs#index'
  get '/galleries/:id/programs', to: 'programs#index'
  get '/galleries/:id/programs/new', to: 'programs#new'
  post '/galleries/:id/programs', to: 'programs#create'
  get '/programs/:id', to: 'programs#show', as: 'program'
  get '/programs/:id/edit', to: 'programs#edit'
  patch '/programs/:id', to: 'programs#update'
  delete '/programs/:id', to: 'programs#destroy'
  #museums routes
  get '/museums', to: 'museums#index'
  get '/museums/new', to: 'museums#new'
  post '/museums', to: 'museums#create'
  get '/museums/:id', to: "museums#show"
  get '/museums/:id/edit', to: "museums#edit"
  patch '/museums/:id', to: 'museums#update'
  delete '/museums/:id', to:'museums#destroy'
  get '/museums/:id/works', to: 'museums#works'
  get '/museums/:id/works/new', to: 'works#new'

  # works routes
  get '/works', to: 'works#index'
  post '/museums/:id/works', to: 'works#create'
  get 'works/:id', to: 'works#show'
  get '/works/:id/edit', to: 'works#edit'
  patch '/works/:id', to: 'works#update'
  delete '/works/:id', to: 'works#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :programs, dependent: :destroy

  def self.select_rooms(params_capacity, params_sort)
    if params_sort
      select("galleries.*, COUNT(*) AS count")
      .left_outer_joins(:programs)
      .group(:id)
      .where('capacity > ?', params_capacity)
      .order(count: :desc, tech_support: :desc, created_at: :desc)
    else
      where('capacity > ?', params_capacity)
      .order(tech_support: :desc, created_at: :desc)
    end
  end
end

app/models/museum.rb
class Museum < ApplicationRecord
  has_many :works, dependent: :destroy

  def total_works
    works.count
  end
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :gallery

  def self.select_programs(params_id, params_participants, params_sort)
    if params_id
      where(gallery_id: params_id)
      .where('number_of_participants > ?', params_participants.to_i)
      .order(params_sort, created_at: :desc)
    else
      where('number_of_participants > ?', params_participants.to_i)
      .order(params_sort, created_at: :desc)
    end
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :museum
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    if params[:sort]
      @galleries = Gallery.select("galleries.*, COUNT(*) AS count")
                                  .left_outer_joins(:programs)
                                  .group(:id)
                                  .where('capacity > ?', params[:capacity]|| 0)
                                  .order(count: :desc, tech_support: :desc, created_at: :desc)
    else
      @galleries = Gallery.where('capacity > ?', params[:capacity]|| 0).order(tech_support: :desc, created_at: :desc)
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
  end

  def create
    Gallery.create(gallery_params)

    redirect_to '/galleries'
  end

  def edit
     @gallery = Gallery.find(params[:id])
  end

   def update
     Gallery.find(params[:id]).update(gallery_params)

     redirect_to params[:previous_request]
   end

   def destroy
     Gallery.destroy(params[:id])
     redirect_to '/galleries'
   end

   private

   def gallery_params
     params.permit(:name, :has_projector, :capacity)
   end
 end

app/controllers/gallery_programs_controller.rb
class GalleriesProgramsController < ApplicationController

  def index
    @gallery = Gallery.find(params[:id])
    if params[:sort]
      @programs = @gallery.programs.sort_alphabetically
    else
      @programs = @gallery.programs
    end
  end

  def new
    @gallery = Gallery.find(params[:id])
  end

  def create
    @gallery = Gallery.find(params[:id])
    @gallery.programs.create(name: params[:name])
    redirect_to "/galleries/#{@gallery.id}/programs"
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
    # @museums = Museum.all.order(created_at: :desc)
    @museums = Museum.order(created_at: :desc)
  end

  def new

  end

  def create
    museum = Museum.new({
      name: params[:museum][:name],
      city: params[:museum][:city],
      admission_cost: params[:museum][:admission_cost],
      old_masters: params[:museum][:old_masters],
      architect: params[:museum][:architect]
      })
    museum.save
    redirect_to "/museums"
  end

  def show
    @museum = Museum.find(params[:id])
  end

  def edit
    @museum = Museum.find(params[:id])
  end

  def update
    museum = Museum.find(params[:id])
    museum.update({
      name: params[:museum][:name],
      city: params[:museum][:city],
      admission_cost: params[:museum][:admission_cost],
      old_masters: params[:museum][:old_masters],
      architect: params[:museum][:architect]
      })
    museum.save
    redirect_to "/museums/#{museum.id}"
  end

  def destroy
    Museum.destroy(params[:id])
    redirect_to '/museums'
  end

  def works
    @museum = Museum.find(params[:id])
    if params.include?(:greater_than)
      @works = @museum.works.where('year > ?', params[:greater_than].to_i)
    else
      @works = @museum.works.order(params[:sort])
    end
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    @programs = Program.where('number_of_participants > ?', params[:number_of_participants]|| 0).order(params[:sort], created_at: :desc)
  end

  def show
    @program = Program.find(params[:id])
  end

  def new

  end

  def create
    Program.create(programs_params)

    redirect_to "/galleries/#{params[:id]}/programs"
  end

  def edit
    @program = Program.find(params[:id])
  end

  def update
    Program.find(params[:id]).update(programs_params)
    redirect_to params[:previous_request]
  end

  def destroy
    Program.destroy(params[:id])
    redirect_to params[:previous_request]
  end

  private

  def programs_params
    params.permit(:gallery_id, :name, :number_of_participants).merge(params[:program])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.where(on_display: "true")
  end

  def new

  end

  def create
    work = Work.new({
      name: params[:work][:name],
      artist: params[:work][:artist],
      year: params[:work][:year],
      on_display: params[:work][:on_display],
      medium: params[:work][:medium],
      museum_id: params[:work][:museum_id]
      })
    work.save
    redirect_to "/museums/#{work.museum_id}/works"
  end

  def show
    @work = Work.find(params[:id])
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    work = Work.find(params[:id])
    work.update({
      name: params[:work][:name],
      artist: params[:work][:artist],
      year: params[:work][:year],
      on_display: params[:work][:on_display],
      medium: params[:work][:medium]
      })
    work.save
    redirect_to "/works/#{work.id}"
  end

  def destroy
    Work.destroy(params[:id])
    redirect_to '/works'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%b %d, %Y")
  end

  def format_timestamp(date)
    date.strftime('%m-%d-%Y %H:%M')
  end
end

app/views/galleries/edit.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h1>Update Gallery </h1>

<%= form_tag "/galleries/#{@gallery.id}", method: :patch do %>
  <%= hidden_field_tag :previous_request, request.referrer %>
  <%= label_tag "Gallery name" %>
  <%= text_field_tag :name, @gallery.name %><br>

  <%= label_tag :capacity %>
  <%= number_field_tag :capacity, @gallery.capacity %><br>

  <%= label_tag :tech_support %>
  <%= hidden_field_tag :tech_support, false %>
  <%= check_box_tag :tech_support, true, @gallery.tech_support %><br>
  <%= submit_tag "Update Gallery" %>
<% end %>

app/views/galleries/index.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h1>All Galleries</h1>
<%= link_to "New Gallery", "/galleries/new" %><br>

<%= form_tag '/galleries', method: :get do %>
<p><%= link_to 'Sort by Number of Programs', "/galleries?sort=true" %></p>
<%= submit_tag 'Only return records with more than the minimum capacity' %>
  <%= number_field_tag :capacity %>
<% end %>
<% @galleries.each_with_index do |gallery, index|%>
  <div id="<%= "row-#{index}" %>">
    <hr>
    <h2>Name: <%= link_to gallery.name, "/galleries/#{gallery.id}" %> </h2>
    <h4>Capacity: <%= gallery.capacity %></h4>
    <p><%= "#{gallery.programs.count} programs" %></p>
    <p>Supports Technology: <%= gallery.tech_support %></p>

  <p><%= link_to "Update Gallery", "/galleries/#{gallery.id}/edit" %></p>
  <%= button_to 'Delete Gallery', "/galleries/#{gallery.id}", method: :delete%><br>
  </div>
<% end %>

app/views/galleries/new.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h1>New Gallery</h1><br>

<%= form_tag '/galleries' do %>
  <%= label_tag  "Gallery name"%>
  <%= text_field_tag :name %><br>

  <%= label_tag :capacity %>
  <%= number_field_tag :capacity %><br>

  <%= label_tag :tech_support %>
  <%= hidden_field_tag :tech_support, false %>
  <%= check_box_tag :tech_support, true %><br>

  <%= submit_tag "Create Gallery" %>
<% end %>

app/views/galleries/show.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h1>Name: <%= link_to @gallery.name, request.path %></h1>
<p>Capacity: <%= @gallery.capacity %></p>
<p>Supports Technology: <%= @gallery.tech_support %></p>
<p><%= "#{@gallery.programs.count} programs" %></p>

<h3><%= link_to "View Galleries", "/galleries/#{@gallery.id}/programs" %></h3>
<h3><%= link_to "Update Gallery", "/galleries/#{@gallery.id}/edit"%></h4>
<%= button_to 'Delete Gallery', "/galleries/#{@gallery.id}", method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelationalRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/museums/edit.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<form action="/museums/<%= @museum.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH" />
  <p>Museum name:</p>
  <input type='text' name='museum[name]' value='<%= @museum.name %>'/><br/>
  <p>City:</p>
  <input type='text' name='museum[city]' value='<%= @museum.city %>'/><br/>
  <p>Admission Cost:</p>
  <input type='number' min=0 name='museum[admission_cost]' value='<%= @museum.admission_cost %>'/><br/>
  <p>Works by old masters:</p>
  <input type="radio" id='yes' name="museum[old_masters]" value="true">
  <label for="yes">Yes</label><br>
  <input type="radio" id ='no' name="museum[old_masters]" value="false">
  <label for="no">No</label><br>
  <p>Architect:</p>
  <input type='text' name='museum[architect]' value='<%= @museum.architect %>'/><br/>
  <input type='submit' name='Submit'/>
</form>

app/views/museums/index.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<h1>All Museums</h1>

<a href="/museums/new">New Museum</a></li>

<% @museums.each do |museum| %>
  <h2><a href="/museums/<%= museum.id %>"><%= museum.name%></a></h2>
  <%= button_to 'Delete Museum', "/museums/#{museum.id}", method: :delete %> <%= button_to 'Edit Museum', "/museums/#{museum.id}/edit", method: :get %>
<% end %>

app/views/museums/new.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<form action="/museums" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>Museum name:</p>
  <input type='text' name='museum[name]'/><br/>
  <p>City:</p>
  <input type='text' name='museum[city]'/><br/>
  <p>Admission Cost:</p>
  <input type='number' min=0 max='150' name='museum[admission_cost]'/><br/>
  <p>Works by old masters:</p>
  <input type="radio" id='yes' name="museum[old_masters]" value="true">
  <label for="yes">Yes</label><br>
  <input type="radio" id ='no' name="museum[old_masters]" value="false">
  <label for="no">No</label><br>
  <p>Architect:</p>
  <input type='text' name='museum[architect]'/><br/>
  <input type='submit' name='Submit'/>
</form>

app/views/museums/show.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<h1><%= @museum.name %></h1>
<p> City: <%= @museum.city %></p>
<p> Admission Cost: <%= @museum.admission_cost %></p>
<p> Displays Works By Old Masters: <%= @museum.old_masters %></p>
<p>Architect: <%= @museum.architect %></p>
<p> Total Works: <%= @museum.total_works %></p>
<%= button_to "See all works at #{@museum.name}", "/museums/#{@museum.id}/works", method: :get %>
<a href="/museums/<%= @museum.id %>/edit">Edit</a>
<form action="/museums/<%= @museum.id %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="delete"/>
</form>

app/views/museums/works.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<h1>All Works of Art at <%=@museum.name%></h1>

<%= link_to "Sort Alphabetically", :sort => 'name' %>

<%= form_with url: "/museums/#{@museum.id}/works", method: :get, local: true do |form| %>
  <p> Only display works created after: </p>
  <%= number_field_tag :greater_than %>
  <%= form.submit "Submit" %>
<% end %>

<% @works.each do |work| %>
  <h3><a href="/works/<%= work.id %>"><%= work.name%></a></h3>
  <p> Artist: <%= work.artist %></p>
  <p> Year Created: <%= work.year %></p>
  <p> On Display: <%= work.on_display %></p>
  <p> Medium: <%= work.medium %></p>
  <%= button_to 'Delete Work', "/works/#{work.id}", method: :delete %>
  <%= button_to 'Edit Work', "/works/#{work.id}/edit", method: :get %>
<% end %>
</br>
<a href="/museums/<%= @museum.id %>/works/new">Create New Work</a>

app/views/programs/edit.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h1>Update Program <%= @program.name %></h1>

  <%= form_tag "/programs/#{@program.id}", method: :patch do %>
  <%= hidden_field_tag :previous_request, request.referrer %>
  <%= label_tag "Program name: " %>
  <%= text_field_tag :name, @program.name %><br>

  <%= label_tag :number_of_participants %>
  <%= number_field_tag :number_of_participants, @program.number_of_participants %><br>
  
  <%= submit_tag "Update Program"  %>
<% end %>

app/views/programs/index.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h1>Programs</h1>
<p><%= "#{@programs.count} programs" %></p>

<% if params[:id] %>
<%= link_to "Create Program", "/galleries/#{params[:id]}/programs/new" %>
<% end %>

<%= form_tag '/programs', method: :get do %>
  <% if params[:id] %>
    <%= hidden_field_tag :id, params[:id] %>
  <% end %>
  <%= submit_tag 'Only return records with more than minimum participants' %>
  <%= number_field_tag :number_of_participants %>
<% end %>


<table>
  <tr>
    <th> Name <br> <%= link_to "Sort Alphabetically", :sort=>"name" %> </th>
    <th> Gallery </th>
    <th> Total Participants </th>
    <th> Created </th>
    <th> Update </th>
    <th> Delete </th>
  </tr>

  <% @programs.each_with_index do |program, index| %>
    <tr id=<%= "row-#{index}" %>>
    <td><%= link_to program.name, "/programs/#{program.id}" %></td>
    <td><%= link_to program.gallery.name, "/galleries/#{program.gallery_id}" %></td>
    <td><%= program.number_of_participants %></td>
    <td><%= format_timestamp(program.created_at) %></td>
    <td><%= link_to "Update Program", "/programs/#{program.id}/edit" %></td>
    <td><%= button_to "Delete Program", program_path(program, previous_request: request.path), method: :delete %></td>
    </tr>
<% end %>
<br>
</table>

app/views/programs/new.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h1>New Program</h1>

  <%= form_tag "/galleries/#{params[:id]}/programs" do %>
  <%= hidden_field_tag :gallery_id, params[:id] %>
  <%= label_tag "Program name: " %>

  <%= text_field_tag :name %><br>
  <%= label_tag :number_of_participants %>

  <%= number_field_tag :number_of_participants %><br>
  <%= submit_tag "Create Program"  %>
<% end %>

app/views/programs/show.html.erb
<header>
  <nav>
    <a href="/">Art Museum Manager</a>
    <a href='/museums'>Museums</a>
    <a href='/works'>Works</a>
    <a href='/galleries'>Galleries</a>
    <a href='/programs'>Programs</a>
  </nav>
</header>

<h3>Program name: <%= link_to @program.name, "/programs/#{@program.id}" %> </h3>
<h4>Gallery name: <%= link_to @program.gallery.name, "/galleries/#{@program.gallery.id}" %></h4>
<p>Number of Participants: <%= @program.number_of_participants %></p>

<h4><%= link_to 'Update Program', "/programs/#{@program.id}/edit" %></h4>
<h1><%= button_to 'Delete Program', program_path(@program, previous_request: request.referrer), method: :delete %></h1>

app/views/welcome/index.html.erb
<h1>Art Museum Manager</h1>
<ul>
  <li><a href="/museums">Museums index</a></li>
  <li><a href="/works">Works index</a></li>

  <li><a href="/galleries">Galleries index</a></li>
  <li><a href="/programs">Program index</a></li>

</ul>

app/views/works/edit.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<form action="/works/<%= @work.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH" />
  <p>work name:</p>
  <input type='text' name='work[name]' value='<%= @work.name %>'/><br/>
  <p>Artist:</p>
  <input type='text' name='work[artist]' value='<%= @work.artist %>'/><br/>
  <p>Year Created:</p>
  <input type='number' min=0 name='work[year]' value='<%= @work.year %>'/><br/>
  <p>On Display:</p>
  <input type="radio" id='yes' name="work[on_display]" value="true">
  <label for="yes">Yes</label><br>
  <input type="radio" id ='no' name="work[on_display]" value="false">
  <label for="no">No</label><br>
  <p>Medium:</p>
  <input type='text' name='work[medium]' value='<%= @work.medium %>'/><br/>
  <input type='submit' name='Submit'/>
</form>

app/views/works/index.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<h1>All Works of Art</h1>

<% @works.each do |work| %>
  <h3><a href="/works/<%= work.id %>"><%= work.name%></a></h3>
  <%= button_to 'Delete Work', "/works/#{work.id}", method: :delete %>
  <%= button_to 'Edit Work', "/works/#{work.id}/edit", method: :get %>
<% end %>

app/views/works/new.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<form action="/museums/<%= params[:id] %>/works" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>Name of Work:</p>
  <input type='text' name='work[name]'/><br/>
  <p>Artist:</p>
  <input type='text' name='work[artist]'/><br/>
  <p>Year Created:</p>
  <input type='number' min='-5000' max='2021' name='work[year]'/><br/>
  <p>On Display:</p>
  <input type="radio" id='yes' name="work[on_display]" value="true">
  <label for="yes">Yes</label><br>
  <input type="radio" id ='no' name="work[on_display]" value="false">
  <label for="no">No</label><br>
  <p>Medium:</p>
  <input type='text' name='work[medium]'/><br/>
  <input type="hidden" name="work[museum_id]" value="<%= params[:id] %>">
  <input type='submit' name='Submit'/>
</form>

app/views/works/show.html.erb
<nav>
  <a href="/museums">Museum Index</a>
  <a href="/works">Artwork Index</a>
</nav>
<h1><%= @work.name %></h1>
<p> Artist: <%= @work.artist %></p>
<p> Year Created: <%= @work.year %></p>
<p> On Display: <%= @work.on_display %></p>
<p> Medium: <%= @work.medium %></p>
<a href="/works/<%= @work.id %>/edit">Edit</a>
<form action="/works/<%= @work.id %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="delete"/>
</form>